# Generated by Django 4.2.5 on 2023-10-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
