# Generated by Django 4.2.5 on 2023-10-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_curator',
            field=models.BooleanField(default=False),
        ),
    ]
