# Generated by Django 4.2.5 on 2023-10-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_review_is_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(),
        ),
    ]
